spring.application.name=biblioteca
spring.datasource.url=jdbc:h2:file:./data/biblioteca;AUTO_SERVER=TRUE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
app.cors.allowed-origins=http://localhost:4200
